version: '3.1'

services:
  vehicle-service:
    image: babuwant2do/vehicles-fleet-manager:0.0.1-SNAPSHOT
    container_name: vehicle-service
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_HOST=vehicle-db
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=vehicles-fleet_db
    depends_on:
      - vehicle-db

  vehicle-db:
    image: mongo:4.0
    container_name: vehicle-db
    restart: always
    ports:
      - 12345:27017
    volumes:
      - mongo-data-vol:/data/db

volumes:
  mongo-data-vol:
    external:
      name: vehicle-mongo-data-volume

networks:
  default:
    external:
      name: vehicle-net